

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//alias를 이용하여 src폴더를 기준으로 경로를 작성
import Navbar from "@/components/Navbar";

import getCurrentUser from "./actions/getCurrentUser";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        
          <Navbar currentUser={currentUser}></Navbar>
          {children}
          <Script
            src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7e994a2eea7534f2ee6b9d52d2bc13d7&libraries=services,clusterer&autoload=false"
          ></Script>
        
        </body>
    </html>
  );
}
