'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//alias를 이용하여 src폴더를 기준으로 경로를 작성
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar></Navbar>
          {children}
        </SessionProvider>
        </body>
    </html>
  );
}
